### PR TITLE
Major Rework

### PR DESCRIPTION
**Pull request by benzman81**
Hi,

I did a lot of changes and fixes that make the plugin work better, especially in regards to webhooks.
 Added configuration for "cacheDirectory", "pingInterval", and "ignoreReEnterExitSeconds".
 Some clean code was also done.

Would be great to see this code merged.

Regards,
 Markus

### CODE REVIEW

**Comment by PeteLawrence** [comment]
Nice work. I'll try to look at this tonight, but may have to wait until after Boxing Day.

**Comment by benzman81** [comment]
Maybe you wait a bit, I am currently rebuilding it as platform :-))

**Comment by benzman81** [comment]
Now implemented as platform.

**Comment by erfinb** [comment]
Man, you are on fire! Thank you for all of your hard work!!!!

**Comment by erfinb** [comment]
Hey! The only problem I am having is that the push to HomeKit doesn't seem to consistently fire off when the actual person occupation shows up in homebridge. Is this a HomeKit issue?

**Comment by erfinb** [comment]
I am noticing this mostly because after I open the home app a while after someone enters the area and I have verified via homebridge that this plugin has seen them, then after opening the Home app it recognizes that someone has occupied the area. Does that make sense?

**Comment by benzman81** [comment]
@erfinb I am having the same issue since a few days. I am trying to track the issue down to a cause. Things I changed before this happend: added a wifi repeator to my network, updated to iOS 10.2, installed the people plugin (original and my new implementation). I know removed the people plugin completly, but the issue persists with notifications for my other plugins. Now removed the repeater to see if that helps, but also might be an iOS 10.2 issue. I opened an issue in the homebridge project, but noone has commented having the same issue yet.

**Comment by benzman81** [comment]
In "Not Refreshing Until Checked #27" you and others are commenting the same with the original plugin, so shouldnt be caused by my changes.

**Comment by benzman81** [comment]
Now, webhooks are never outdated. A ping only triggers a change if at least one time a successful ping was done after a webhook was called.

**Comment by wr** [comment]
nice! really appreciate your hard work on this plugin :)

**Comment by benzman81** [comment]
Great!

**Comment by PeteLawrence** [comment]
Thanks for all your work on this, I've just published v0.5 which includes all of this work.

**Pull request merged**
